Medienreaktor:
  Meilisearch:
    ContentRepositoryQueueIndexer:
      enableLiveAsyncIndexing: true
      # Change size of single batch jobs via this setting
      batchSize: 50

      # Number of failed jobs accepted to switch the alias to the new index
      # -1 means, accept any number of failures
      acceptedFailedJobs: 0

      # Run a nodeindex:cleanup after the node switching job switched the index
      cleanupIndicesAfterSuccessfulSwitch: true
Flowpack:
  JobQueue:
    Common:
      queues:
        'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer':
          preset: 'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer'
          options:
            tableName: 'flowpack_jobqueue_QueueIndexer'
        'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer.Live':
          preset: 'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer.Live'
          options:
            tableName: 'flowpack_jobqueue_QueueIndexerLive'
      presets:
        'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer':
          className: 'Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue'
        'Medienreaktor.Meilisearch.ContentRepositoryQueueIndexer.Live':
          className: 'Flowpack\JobQueue\Doctrine\Queue\DoctrineQueue'
